version: '2'

services:
  web:
    build: ./
    depends_on: ["db"]
    ports: ["8080:80"]
    volumes: ["./:/var/www/html"]

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root

